"""add anthropic_api_key to users

Revision ID: 18a03e8cf3e1
Revises: 4fb8ed835417
Create Date: 2026-03-17 07:22:00.287457

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a03e8cf3e1'
down_revision: Union[str, None] = '4fb8ed835417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_api_key')
    # ### end Alembic commands ###
