"""add preview_url error_message summary to sessions

Revision ID: 2e14cbee816e
Revises: 18a03e8cf3e1
Create Date: 2026-03-20 03:42:02.163073

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e14cbee816e'
down_revision: Union[str, None] = '18a03e8cf3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('preview_url', sa.String(length=500), nullable=True))
    op.add_column('sessions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'summary')
    op.drop_column('sessions', 'error_message')
    op.drop_column('sessions', 'preview_url')
    # ### end Alembic commands ###
